Add support for ZADD GT/LT options
lettuce-io/lettuce-core pull request #1455
Opened 2020-10-10 06:46 UTC by dengliming

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [ ] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

 

closes [https://github.com/lettuce-io/lettuce-core/issues/1451](https://github.com/lettuce-io/lettuce-core/issues/1451)

2020-10-12 14:06 UTC, mp911de requested changes
Thanks a lot, great work. Can you add also `@since` tags (version 6.1) to all newly introduced `public` methods in `ZAddArgs` and yourself as `@author`?

I think we also need a guard to the `@Test` methods when running the tests against an older Redis version, but I currently don't have a good idea. Maybe it's time to introduce `@EnabledOnRedisVersion`. Happy for suggestions.

2020-10-12 14:06 UTC, mp911de commented on src/main/java/io/lettuce/core/ZAddArgs.java
> +        this.gt = true;
ideally, we set `lt` to `false` to not have a state where `lt` and `gt` are both set to true if someone calls `lt().gt()`.

2020-10-12 15:27 UTC, dengliming commented
> Maybe it's time to introduce @EnabledOnRedisVersion.

@mp911de Great idea. Maybe we should track this with separated issue?

2020-10-26 09:49 UTC, mp911de commented
For now, we can guard the tests with `@EnabledOnCommand("ZMSCORE")` since `ZMSCORE` was added in Redis 6.2, too.

2020-10-26 09:52 UTC, dengliming commented
Thanks. will update it later.

2020-10-26 09:55 UTC, mp911de commented
No worries, I'm about to merge and polish up this PR.

2020-10-26 10:02 UTC, mp911de commented
Thank you for your contribution. That's merged and polished now.

2020-10-26 10:02 UTC, closed without merging